[package]
name = "cfy-dev/rng-class"
version = "1.0.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
description = "A simple, yet good lightweight RNG class module."

[dependencies]
